theme = "base16_transparent"

[editor]
line-number = "relative"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "selections"]
right = ["diagnostics", "position"]
