[language-server.rust-analyzer.config]
[inlayHints]
bindingModeHints.enable = true
chainingHints.enable = true
closingBraceHints.enable = true
closureCaptureHints.enable = true
closureReturnTypeHints.enable = "always"
discriminantHints.enable = "always"
expressionAdjustmentHints.enable = "always"
implicitDrops.enable = true
lifetimeElisionHints.enable = "always"
lifetimeElisionHints.useParameterNames = true
maxLength = 25
rangeExclusiveHints.enable = true
reborrowHints.enable = true
typeHints.enable = true
