use-grammars = { only = [
    "astro",
    "awk",
    "bash",
    "c",
    "cmake",
    "comment",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "dot",
    "env",
    "git-attributes",
    "git-commit",
    "git-config",
    "git-ignore",
    "git-rebase",
    "go",
    "gomod",
    "hcl",
    "html",
    "ini",
    "javascript",
    "jsdoc",
    "json",
    "jsx",
    "make",
    "markdown",
    "markdown.inline",
    "nu",
    "prisma",
    "python",
    "rust",
    "sql",
    "sshclientconfig",
    "svelte",
    "tfvars",
    "toml",
    "tsx",
    "typescript",
    "yaml",
  ]}

[[language]]
name = "astro"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "awk"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "c"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "cmake"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "comment"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "cpp"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "css"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "diff"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "dockerfile"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "dot"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "env"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "git-attributes"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "git-commit"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "git-config"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "git-ignore"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "git-rebase"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "go"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "gomod"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "hcl"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "html"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "ini"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "javascript"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-server = {command = "typescript-language-server", args = ["--stdio", "--log-level", "4"], language-id = "javascript"}

[[language]]
name = "jsdoc"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "json"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "jsx"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-server = {command = "typescript-language-server", args = ["--stdio", "--log-level", "4"], language-id = "javascriptreact"}

[[language]]
name = "make"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "markdown.inline"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "nu"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "prisma"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "python"
indent = { tab-width = 2, unit = "  " }
auto-format = true
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args=["--stdio"] }
formatter = { command = "black", args = ["--quiet", "-"] }
config = {}

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "sql"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "sshclientconfig"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "svelte"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "tfvars"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "toml"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-server = {command = "typescript-language-server", args = ["--stdio", "--log-level", "4"], language-id = "typescriptreact"}

[[language]]
name = "typescript"
indent = { tab-width = 2, unit = "  " }
auto-format = true
language-server = {command = "typescript-language-server", args = ["--stdio", "--log-level", "4"], language-id = "typescript"}

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }
auto-format = true
